image: "hub.ricebook.net/base/alpine:openresty-2016.12.02"
variables:
    CITADEL_AUTH_TOKEN: $CITADEL_AUTH_TOKEN
    CITADEL_URL: "http://citadel.ricebook.net"
    SSO_URL: "http://sso.ricebook.net"
    MIMIRON_URL: "http://mimiron.ricebook.net"
stages:
    - "build"
build_job:
    stage: "build"
    only:
        - "master"
    script:
        - "corecli register"
        - "corecli build"
pages:
    image: "hub.ricebook.net/base/centos:F2E-2017.03.31"
    stage: "build"
    script:
      - "npm install -g gitbook-cli"
      - "gitbook build . public"
    artifacts:
      paths:
        - public