appname: "erulb"
subscribers: "#inferno"
entrypoints:
  release-host:
    privileged: true
    cmd: "/home/erulb/start.sh"
    ports:
      - "80/tcp"
    network_mode: "host"
build:
  - "mkdir -p /home/erulb/server/logs"
base: "hub.ricebook.net/base/alpine:openresty-2016.12.02"
