appname: "erulb3"
entrypoints:
  release-host:
    privileged: true
    cmd: "/home/erulb3/start.sh"
    ports:
      - "80/tcp"
    network_mode: "host"
build:
  - "mkdir -p /home/erulb3/server/logs"
base: "hub.ricebook.net/base/alpine:openresty-2016.12.02"