appname: "erulb3"
entrypoints:
  release-host:
    privileged: true
    cmd: "nginx -p /erulb/server -c /erulb/conf/release.conf"
    ports:
      - "80/tcp"
    network_mode: "host"
    beta-host:
      privileged: true
      cmd: "nginx -p /erulb/server -c /erulb/conf/dev.conf"
      ports:
        - "80/tcp"
      network_mode: "host"
    xff-host:
      privileged: true
      cmd: "nginx -p /erulb/server -c /erulb/conf/xff.conf"
      ports:
        - "80/tcp"
      network_mode: "host"
build:
  - "mkdir -p /erulb/server/logs"
base: "hub.ricebook.net/base/alpine:openresty-2016.09.05"
